2024-07-19 10:02:55,477 p=269477 u=core n=ansible | 15.207.98.106 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "cache_update_time": 1721383047,
    "cache_updated": false,
    "changed": false
}
2024-07-19 10:02:55,632 p=269477 u=core n=ansible | 13.201.189.227 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "cache_update_time": 1721383046,
    "cache_updated": false,
    "changed": false
}
2024-07-19 10:18:36,082 p=269753 u=core n=ansible | ERROR! the field 'hosts' is required but was not set
2024-07-19 10:20:49,526 p=269814 u=core n=ansible | PLAY [Update and upgrade apt packages] *********************************************************************************************************************************************
2024-07-19 10:20:49,536 p=269814 u=core n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************************
2024-07-19 10:20:57,496 p=269814 u=core n=ansible | ok: [13.201.189.227]
2024-07-19 10:20:57,627 p=269814 u=core n=ansible | ok: [15.207.98.106]
2024-07-19 10:20:57,650 p=269814 u=core n=ansible | TASK [Update and upgrade packages] *************************************************************************************************************************************************
2024-07-19 10:21:03,140 p=269814 u=core n=ansible | [WARNING]: The value "True" (type bool) was converted to "'True'" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

2024-07-19 10:21:03,141 p=269814 u=core n=ansible | ok: [13.201.189.227]
2024-07-19 10:21:03,498 p=269814 u=core n=ansible | ok: [15.207.98.106]
2024-07-19 10:21:03,520 p=269814 u=core n=ansible | PLAY RECAP *************************************************************************************************************************************************************************
2024-07-19 10:21:03,520 p=269814 u=core n=ansible | 13.201.189.227             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-19 10:21:03,521 p=269814 u=core n=ansible | 15.207.98.106              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-19 10:37:54,649 p=270079 u=core n=ansible | PLAY [Install and configure Nginx for static website hosting] **********************************************************************************************************************
2024-07-19 10:37:54,662 p=270079 u=core n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************************
2024-07-19 10:38:03,198 p=270079 u=core n=ansible | ok: [13.201.189.227]
2024-07-19 10:38:03,242 p=270079 u=core n=ansible | ok: [15.207.98.106]
2024-07-19 10:38:03,258 p=270079 u=core n=ansible | TASK [Install Nginx] ***************************************************************************************************************************************************************
2024-07-19 10:38:29,500 p=270079 u=core n=ansible | changed: [13.201.189.227]
2024-07-19 10:38:33,531 p=270079 u=core n=ansible | changed: [15.207.98.106]
2024-07-19 10:38:33,543 p=270079 u=core n=ansible | TASK [Ensure Nginx is running] *****************************************************************************************************************************************************
2024-07-19 10:38:37,979 p=270079 u=core n=ansible | ok: [13.201.189.227]
2024-07-19 10:38:38,038 p=270079 u=core n=ansible | ok: [15.207.98.106]
2024-07-19 10:38:38,060 p=270079 u=core n=ansible | PLAY RECAP *************************************************************************************************************************************************************************
2024-07-19 10:38:38,061 p=270079 u=core n=ansible | 13.201.189.227             : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-19 10:38:38,061 p=270079 u=core n=ansible | 15.207.98.106              : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-22 05:54:35,425 p=325655 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 05:54:35,426 p=325655 u=core n=ansible | 43.204.227.123 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 43.204.227.123 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627670.9710257-325657-235452147308916/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627670.9710257-325657-235452147308916/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627670.9710257-325657-235452147308916/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_jy8ncv32/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 05:55:30,612 p=325655 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-22 05:56:04,477 p=325683 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 05:56:04,478 p=325683 u=core n=ansible | 43.204.227.123 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 43.204.227.123 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627760.314787-325685-136847062659631/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627760.314787-325685-136847062659631/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627760.314787-325685-136847062659631/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_rnhssuzi/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 05:56:07,798 p=325683 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 05:56:07,799 p=325683 u=core n=ansible | 13.234.21.204 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627763.7801085-325686-157896062546403/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627763.7801085-325686-157896062546403/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627763.7801085-325686-157896062546403/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_byn0t00e/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 05:58:19,415 p=325752 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 05:58:19,416 p=325752 u=core n=ansible | 13.234.21.204 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627895.2865524-325755-28309402142788/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627895.2865524-325755-28309402142788/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627895.2865524-325755-28309402142788/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_r5unt860/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 05:58:19,892 p=325752 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 05:58:19,892 p=325752 u=core n=ansible | 43.204.227.123 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 43.204.227.123 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627895.8048828-325754-43025342752684/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627895.8048828-325754-43025342752684/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721627895.8048828-325754-43025342752684/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_aswrdqu9/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 05:58:38,043 p=325808 u=core n=ansible | [WARNING]: Could not match supplied host pattern, ignoring: list-hosts

2024-07-22 05:58:38,044 p=325808 u=core n=ansible | [WARNING]: No hosts matched, nothing to do

2024-07-22 05:58:38,047 p=325808 u=core n=ansible | ERROR! No argument passed to command module
2024-07-22 05:58:53,418 p=325809 u=core n=ansible |   hosts (2):
2024-07-22 05:58:53,418 p=325809 u=core n=ansible |     43.204.227.123
2024-07-22 05:58:53,418 p=325809 u=core n=ansible |     13.234.21.204
2024-07-22 06:00:57,985 p=325828 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 06:00:57,987 p=325828 u=core n=ansible | 13.234.21.204 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628053.8526363-325831-22609828872523/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628053.8526363-325831-22609828872523/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628053.8526363-325831-22609828872523/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_ofj_lgk8/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 06:00:58,009 p=325828 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 06:00:58,011 p=325828 u=core n=ansible | 43.204.227.123 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 43.204.227.123 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628053.7665308-325830-87676604239432/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628053.7665308-325830-87676604239432/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628053.7665308-325830-87676604239432/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_5_zw6n94/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 06:02:43,073 p=325892 u=core n=ansible | PLAY [Update and upgrade apt packages] *********************************************************************************************************************************************
2024-07-22 06:02:43,086 p=325892 u=core n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************************
2024-07-22 06:02:50,261 p=325892 u=core n=ansible | fatal: [43.204.227.123]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "exception": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.6867983-325895-211888193124940/AnsiballZ_setup.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.6867983-325895-211888193124940/AnsiballZ_setup.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.6867983-325895-211888193124940/AnsiballZ_setup.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ansible.legacy.setup_payload_3hpinnby/ansible_ansible.legacy.setup_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n", "failed": true, "module_stderr": "Shared connection to 43.204.227.123 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.6867983-325895-211888193124940/AnsiballZ_setup.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.6867983-325895-211888193124940/AnsiballZ_setup.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.6867983-325895-211888193124940/AnsiballZ_setup.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ansible.legacy.setup_payload_3hpinnby/ansible_ansible.legacy.setup_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
2024-07-22 06:02:50,355 p=325892 u=core n=ansible | fatal: [13.234.21.204]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "exception": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.5526216-325896-77383474023795/AnsiballZ_setup.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.5526216-325896-77383474023795/AnsiballZ_setup.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.5526216-325896-77383474023795/AnsiballZ_setup.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ansible.legacy.setup_payload_aje_25zi/ansible_ansible.legacy.setup_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n", "failed": true, "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.5526216-325896-77383474023795/AnsiballZ_setup.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.5526216-325896-77383474023795/AnsiballZ_setup.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721628165.5526216-325896-77383474023795/AnsiballZ_setup.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ansible.legacy.setup_payload_aje_25zi/ansible_ansible.legacy.setup_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
2024-07-22 06:02:50,358 p=325892 u=core n=ansible | PLAY RECAP *************************************************************************************************************************************************************************
2024-07-22 06:02:50,359 p=325892 u=core n=ansible | 13.234.21.204              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-22 06:02:50,359 p=325892 u=core n=ansible | 43.204.227.123             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-22 06:22:00,267 p=326359 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 06:22:00,269 p=326359 u=core n=ansible | 43.204.227.123 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 43.204.227.123 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629316.1270084-326361-38370989470355/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629316.1270084-326361-38370989470355/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629316.1270084-326361-38370989470355/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_9ngg7q5x/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 06:22:00,781 p=326359 u=core n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 06:22:00,782 p=326359 u=core n=ansible | 13.234.21.204 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629316.5315511-326363-249248734536313/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629316.5315511-326363-249248734536313/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629316.5315511-326363-249248734536313/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_qjgghxyq/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 06:26:57,623 p=326475 u=root n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2024-07-22 06:26:57,625 p=326475 u=root n=ansible | 13.234.21.204 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629613.4391036-326478-107242365230801/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629613.4391036-326478-107242365230801/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629613.4391036-326478-107242365230801/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_uaesa8ac/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 06:27:41,236 p=326475 u=root n=ansible |  [ERROR]: User interrupted execution

2024-07-22 06:28:04,460 p=326506 u=root n=ansible | ansible 2.10.8
  config file = /home/core/Ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
2024-07-22 06:28:04,460 p=326506 u=root n=ansible | Using /home/core/Ansible/ansible.cfg as config file
2024-07-22 06:28:04,465 p=326506 u=root n=ansible | host_list declined parsing /home/core/Ansible/inventory as it did not pass its verify_file() method
2024-07-22 06:28:04,466 p=326506 u=root n=ansible | script declined parsing /home/core/Ansible/inventory as it did not pass its verify_file() method
2024-07-22 06:28:04,466 p=326506 u=root n=ansible | auto declined parsing /home/core/Ansible/inventory as it did not pass its verify_file() method
2024-07-22 06:28:04,469 p=326506 u=root n=ansible | Parsed /home/core/Ansible/inventory inventory source with ini plugin
2024-07-22 06:28:04,485 p=326506 u=root n=ansible | Skipping callback 'default', as we already have a stdout callback.
2024-07-22 06:28:04,485 p=326506 u=root n=ansible | Skipping callback 'minimal', as we already have a stdout callback.
2024-07-22 06:28:04,485 p=326506 u=root n=ansible | Skipping callback 'oneline', as we already have a stdout callback.
2024-07-22 06:28:04,529 p=326506 u=root n=ansible | META: ran handlers
2024-07-22 06:28:04,577 p=326514 u=root n=ansible | <43.204.227.123> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:04,579 p=326514 u=root n=ansible | <43.204.227.123> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b3b612d3e6 43.204.227.123 '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
2024-07-22 06:28:04,587 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:04,588 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b 13.234.21.204 '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
2024-07-22 06:28:06,927 p=326515 u=root n=ansible | <13.234.21.204> (0, b'/home/ubuntu\n', b'')
2024-07-22 06:28:06,928 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:06,929 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b 13.234.21.204 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327 `" && echo ansible-tmp-1721629686.927853-326515-78656228097327="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327 `" ) && sleep 0'"'"''
2024-07-22 06:28:07,217 p=326515 u=root n=ansible | <13.234.21.204> (0, b'ansible-tmp-1721629686.927853-326515-78656228097327=/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327\n', b'')
2024-07-22 06:28:07,351 p=326515 u=root n=ansible | <13.234.21.204> Attempting python interpreter discovery
2024-07-22 06:28:07,351 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:07,352 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b 13.234.21.204 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.9'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.8'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
2024-07-22 06:28:07,636 p=326515 u=root n=ansible | <13.234.21.204> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python3\nENDFOUND\n', b'')
2024-07-22 06:28:07,637 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:07,638 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b 13.234.21.204 '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
2024-07-22 06:28:08,064 p=326515 u=root n=ansible | <13.234.21.204> (0, b'{"platform_dist_result": [], "osrelease_content": "PRETTY_NAME=\\"Ubuntu 24.04 LTS\\"\\nNAME=\\"Ubuntu\\"\\nVERSION_ID=\\"24.04\\"\\nVERSION=\\"24.04 LTS (Noble Numbat)\\"\\nVERSION_CODENAME=noble\\nID=ubuntu\\nID_LIKE=debian\\nHOME_URL=\\"https://www.ubuntu.com/\\"\\nSUPPORT_URL=\\"https://help.ubuntu.com/\\"\\nBUG_REPORT_URL=\\"https://bugs.launchpad.net/ubuntu/\\"\\nPRIVACY_POLICY_URL=\\"https://www.ubuntu.com/legal/terms-and-policies/privacy-policy\\"\\nUBUNTU_CODENAME=noble\\nLOGO=ubuntu-logo\\n"}\n', b'')
2024-07-22 06:28:08,068 p=326515 u=root n=ansible | Using module file /usr/lib/python3/dist-packages/ansible/modules/ping.py
2024-07-22 06:28:08,070 p=326515 u=root n=ansible | <13.234.21.204> PUT /root/.ansible/tmp/ansible-local-3265065u8l282d/tmp7xqo7w50 TO /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py
2024-07-22 06:28:08,072 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b '[13.234.21.204]'
2024-07-22 06:28:09,791 p=326515 u=root n=ansible | <13.234.21.204> (0, b'sftp> put /root/.ansible/tmp/ansible-local-3265065u8l282d/tmp7xqo7w50 /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py\n', b'')
2024-07-22 06:28:09,792 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:09,793 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b 13.234.21.204 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/ /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py && sleep 0'"'"''
2024-07-22 06:28:10,080 p=326515 u=root n=ansible | <13.234.21.204> (0, b'', b'')
2024-07-22 06:28:10,081 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:10,082 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b -tt 13.234.21.204 '/bin/sh -c '"'"'/usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py && sleep 0'"'"''
2024-07-22 06:28:10,818 p=326515 u=root n=ansible | <13.234.21.204> (1, b'Traceback (most recent call last):\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File "/tmp/ansible_ping_payload_9trvs_n0/ansible_ping_payload.zip/ansible/module_utils/basic.py", line 176, in <module>\r\nModuleNotFoundError: No module named \'ansible.module_utils.six.moves\'\r\n', b'Shared connection to 13.234.21.204 closed.\r\n')
2024-07-22 06:28:10,818 p=326515 u=root n=ansible | <13.234.21.204> Failed to connect to the host via ssh: Shared connection to 13.234.21.204 closed.
2024-07-22 06:28:10,820 p=326515 u=root n=ansible | <13.234.21.204> ESTABLISH SSH CONNECTION FOR USER: ubuntu
2024-07-22 06:28:10,821 p=326515 u=root n=ansible | <13.234.21.204> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/core/Keys/KeyPair1_Mumbai.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbc3b11d9b 13.234.21.204 '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/ > /dev/null 2>&1 && sleep 0'"'"''
2024-07-22 06:28:11,105 p=326515 u=root n=ansible | <13.234.21.204> (0, b'', b'')
2024-07-22 06:28:11,112 p=326506 u=root n=ansible | The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py", line 37, in invoke_module
    from ansible.module_utils import basic
  File "/tmp/ansible_ping_payload_9trvs_n0/ansible_ping_payload.zip/ansible/module_utils/basic.py", line 176, in <module>
ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'

2024-07-22 06:28:11,113 p=326506 u=root n=ansible | 13.234.21.204 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 13.234.21.204 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1721629686.927853-326515-78656228097327/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"/tmp/ansible_ping_payload_9trvs_n0/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 176, in <module>\r\nModuleNotFoundError: No module named 'ansible.module_utils.six.moves'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2024-07-22 06:28:39,572 p=326506 u=root n=ansible |  [ERROR]: User interrupted execution

2024-07-22 06:32:28,675 p=327138 u=core n=ansible | 43.204.227.123 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-22 06:32:28,940 p=327138 u=core n=ansible | 13.234.21.204 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-22 06:33:11,930 p=327182 u=core n=ansible |   hosts (2):
2024-07-22 06:33:11,930 p=327182 u=core n=ansible |     43.204.227.123
2024-07-22 06:33:11,930 p=327182 u=core n=ansible |     13.234.21.204
2024-07-22 06:52:30,564 p=327491 u=core n=ansible | PLAY [Update and upgrade apt packages] *********************************************************************************************************************************************
2024-07-22 06:52:30,574 p=327491 u=core n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************************
2024-07-22 06:52:38,857 p=327491 u=core n=ansible | ok: [13.234.21.204]
2024-07-22 06:52:39,162 p=327491 u=core n=ansible | ok: [43.204.227.123]
2024-07-22 06:52:39,188 p=327491 u=core n=ansible | TASK [Update and upgrade packages] *************************************************************************************************************************************************
2024-07-22 06:54:07,371 p=327491 u=core n=ansible | changed: [13.234.21.204]
2024-07-22 06:54:17,899 p=327491 u=core n=ansible | changed: [43.204.227.123]
2024-07-22 06:54:17,921 p=327491 u=core n=ansible | PLAY RECAP *************************************************************************************************************************************************************************
2024-07-22 06:54:17,922 p=327491 u=core n=ansible | 13.234.21.204              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-22 06:54:17,922 p=327491 u=core n=ansible | 43.204.227.123             : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-22 08:31:00,538 p=328978 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - web_servers
      ^ here

2024-07-22 08:33:19,105 p=329024 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - web_servers
      ^ here

2024-07-22 08:35:44,138 p=329076 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - web_servers
      ^ here

2024-07-22 08:36:04,462 p=329080 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - web_servers
    ^ here

2024-07-22 08:36:34,341 p=329090 u=core n=ansible | ERROR! A malformed role declaration was encountered.

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- hosts: all
  ^ here

2024-07-22 08:38:45,148 p=329107 u=core n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 4, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: all
   become: true
         ^ here

2024-07-22 09:22:07,140 p=331508 u=core n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 4, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: all
   become: true
         ^ here

2024-07-22 09:23:45,465 p=331728 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - web_servers
      ^ here

2024-07-22 09:24:56,364 p=331772 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 6, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    roles:
      - web_servers
        ^ here

2024-07-22 09:31:06,288 p=331861 u=core n=ansible | ERROR! the role 'web_servers' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - web_servers
      ^ here

2024-07-22 09:40:36,739 p=332057 u=core n=ansible | ERROR! the role 'test1' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role-specific.yml': line 4, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
   - test1
     ^ here

2024-07-22 09:43:23,593 p=332097 u=core n=ansible | ERROR! the role 'test1' was not found in /home/core/Ansible/playbooks/roles:/home/core/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/core/Ansible/playbooks

The error appears to be in '/home/core/Ansible/playbooks/role.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - test1
      ^ here

2024-07-22 09:46:57,574 p=332161 u=core n=ansible | 43.204.227.123 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-22 09:46:57,611 p=332161 u=core n=ansible | 13.234.21.204 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-22 09:50:28,553 p=332282 u=core n=ansible | PLAY [all] *************************************************************************************************************************************************************************
2024-07-22 09:50:28,564 p=332282 u=core n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************************
2024-07-22 09:50:36,745 p=332282 u=core n=ansible | ok: [43.204.227.123]
2024-07-22 09:50:37,006 p=332282 u=core n=ansible | ok: [13.234.21.204]
2024-07-22 09:50:37,028 p=332282 u=core n=ansible | TASK [test1 : install nginx] *******************************************************************************************************************************************************
2024-07-22 09:51:01,151 p=332282 u=core n=ansible | changed: [43.204.227.123]
2024-07-22 09:51:01,170 p=332282 u=core n=ansible | changed: [13.234.21.204]
2024-07-22 09:51:01,182 p=332282 u=core n=ansible | TASK [test1 : start nginx] *********************************************************************************************************************************************************
2024-07-22 09:51:05,711 p=332282 u=core n=ansible | ok: [13.234.21.204]
2024-07-22 09:51:05,830 p=332282 u=core n=ansible | ok: [43.204.227.123]
2024-07-22 09:51:05,874 p=332282 u=core n=ansible | PLAY RECAP *************************************************************************************************************************************************************************
2024-07-22 09:51:05,874 p=332282 u=core n=ansible | 13.234.21.204              : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-22 09:51:05,875 p=332282 u=core n=ansible | 43.204.227.123             : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-22 10:30:27,701 p=333724 u=core n=ansible | PLAY [all] *******************************************************************************
2024-07-22 10:30:27,712 p=333724 u=core n=ansible | TASK [Gathering Facts] *******************************************************************
2024-07-22 10:30:36,172 p=333724 u=core n=ansible | ok: [43.204.227.123]
2024-07-22 10:30:36,183 p=333724 u=core n=ansible | ok: [13.234.21.204]
2024-07-22 10:30:36,203 p=333724 u=core n=ansible | TASK [test2 : Uninstall Nginx] ***********************************************************
2024-07-22 10:30:49,647 p=333724 u=core n=ansible | changed: [43.204.227.123]
2024-07-22 10:30:50,138 p=333724 u=core n=ansible | changed: [13.234.21.204]
2024-07-22 10:30:50,155 p=333724 u=core n=ansible | TASK [test2 : Install Apache2] ***********************************************************
2024-07-22 10:31:14,430 p=333724 u=core n=ansible | changed: [13.234.21.204]
2024-07-22 10:31:15,272 p=333724 u=core n=ansible | changed: [43.204.227.123]
2024-07-22 10:31:15,290 p=333724 u=core n=ansible | TASK [test2 : Start apache2] *************************************************************
2024-07-22 10:31:19,862 p=333724 u=core n=ansible | ok: [43.204.227.123]
2024-07-22 10:31:19,999 p=333724 u=core n=ansible | ok: [13.234.21.204]
2024-07-22 10:31:20,036 p=333724 u=core n=ansible | PLAY RECAP *******************************************************************************
2024-07-22 10:31:20,036 p=333724 u=core n=ansible | 13.234.21.204              : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-22 10:31:20,037 p=333724 u=core n=ansible | 43.204.227.123             : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-24 06:15:23,075 p=730802 u=core n=ansible | 3.110.101.30 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:16:15,181 p=730802 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-24 06:16:35,427 p=731094 u=core n=ansible | 3.110.101.30 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:16:49,546 p=731094 u=core n=ansible | 13.201.185.232 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:17:00,830 p=731235 u=core n=ansible | 3.110.101.30 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:17:00,882 p=731235 u=core n=ansible | 13.201.185.232 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:21:36,388 p=732243 u=core n=ansible | 35.154.202.43 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:22:03,863 p=732385 u=core n=ansible | 3.110.101.30 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 06:22:03,986 p=732385 u=core n=ansible | 13.201.185.232 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 07:46:16,046 p=751285 u=core n=ansible | PLAY [prod] *****************************************************************************************
2024-07-24 07:46:16,063 p=751285 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 07:46:24,605 p=751285 u=core n=ansible | ok: [3.110.101.30]
2024-07-24 07:46:24,816 p=751285 u=core n=ansible | ok: [13.201.185.232]
2024-07-24 07:46:24,835 p=751285 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 07:46:24,869 p=751285 u=core n=ansible | fatal: [3.110.101.30]: FAILED! => {"msg": "The conditional check ''nginx' not in ansible_facts.packages' failed. The error was: error while evaluating conditional ('nginx' not in ansible_facts.packages): 'dict object' has no attribute 'packages'\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: updating cache and installing apache2\n  ^ here\n"}
2024-07-24 07:46:24,887 p=751285 u=core n=ansible | fatal: [13.201.185.232]: FAILED! => {"msg": "The conditional check ''nginx' not in ansible_facts.packages' failed. The error was: error while evaluating conditional ('nginx' not in ansible_facts.packages): 'dict object' has no attribute 'packages'\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: updating cache and installing apache2\n  ^ here\n"}
2024-07-24 07:46:24,892 p=751285 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 07:46:24,892 p=751285 u=core n=ansible | 13.201.185.232             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 07:46:24,893 p=751285 u=core n=ansible | 3.110.101.30               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 08:50:10,756 p=765438 u=core n=ansible | PLAY [prod] *****************************************************************************************
2024-07-24 08:50:10,768 p=765438 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 08:50:19,050 p=765438 u=core n=ansible | ok: [3.110.101.30]
2024-07-24 08:50:19,190 p=765438 u=core n=ansible | ok: [13.201.185.232]
2024-07-24 08:50:19,211 p=765438 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 08:50:19,243 p=765438 u=core n=ansible | fatal: [3.110.101.30]: FAILED! => {"msg": "The conditional check ''nginx' not in ansible.builtin.package_facts' failed. The error was: error while evaluating conditional ('nginx' not in ansible.builtin.package_facts): 'ansible' is undefined\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: updating cache and installing apache2\n  ^ here\n"}
2024-07-24 08:50:19,261 p=765438 u=core n=ansible | fatal: [13.201.185.232]: FAILED! => {"msg": "The conditional check ''nginx' not in ansible.builtin.package_facts' failed. The error was: error while evaluating conditional ('nginx' not in ansible.builtin.package_facts): 'ansible' is undefined\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: updating cache and installing apache2\n  ^ here\n"}
2024-07-24 08:50:19,263 p=765438 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 08:50:19,264 p=765438 u=core n=ansible | 13.201.185.232             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 08:50:19,265 p=765438 u=core n=ansible | 3.110.101.30               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 08:59:23,759 p=767487 u=core n=ansible | PLAY [prod] *****************************************************************************************
2024-07-24 08:59:23,770 p=767487 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 08:59:32,086 p=767487 u=core n=ansible | ok: [13.201.185.232]
2024-07-24 08:59:32,189 p=767487 u=core n=ansible | ok: [3.110.101.30]
2024-07-24 08:59:32,213 p=767487 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 08:59:32,246 p=767487 u=core n=ansible | fatal: [3.110.101.30]: FAILED! => {"msg": "The conditional check ''nginx' not in ansible_facts.available_packages' failed. The error was: error while evaluating conditional ('nginx' not in ansible_facts.available_packages): 'dict object' has no attribute 'available_packages'\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: updating cache and installing apache2\n  ^ here\n"}
2024-07-24 08:59:32,260 p=767487 u=core n=ansible | fatal: [13.201.185.232]: FAILED! => {"msg": "The conditional check ''nginx' not in ansible_facts.available_packages' failed. The error was: error while evaluating conditional ('nginx' not in ansible_facts.available_packages): 'dict object' has no attribute 'available_packages'\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: updating cache and installing apache2\n  ^ here\n"}
2024-07-24 08:59:32,264 p=767487 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 08:59:32,264 p=767487 u=core n=ansible | 13.201.185.232             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 08:59:32,264 p=767487 u=core n=ansible | 3.110.101.30               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 09:14:09,028 p=770785 u=core n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 2, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: check if nginx is installed
    command: which nginx
           ^ here

2024-07-24 09:15:22,827 p=771098 u=core n=ansible | PLAY [prod] *****************************************************************************************
2024-07-24 09:15:22,838 p=771098 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:15:30,706 p=771098 u=core n=ansible | ok: [3.110.101.30]
2024-07-24 09:15:30,961 p=771098 u=core n=ansible | ok: [13.201.185.232]
2024-07-24 09:15:30,984 p=771098 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:15:34,584 p=771098 u=core n=ansible | fatal: [3.110.101.30]: FAILED! => {"changed": true, "cmd": ["which", "nginx"], "delta": "0:00:00.008625", "end": "2024-07-24 09:15:34.191497", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 09:15:34.182872", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 09:15:34,585 p=771098 u=core n=ansible | ...ignoring
2024-07-24 09:15:34,604 p=771098 u=core n=ansible | fatal: [13.201.185.232]: FAILED! => {"changed": true, "cmd": ["which", "nginx"], "delta": "0:00:00.008651", "end": "2024-07-24 09:15:34.203380", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 09:15:34.194729", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 09:15:34,604 p=771098 u=core n=ansible | ...ignoring
2024-07-24 09:15:34,621 p=771098 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:16:18,300 p=771098 u=core n=ansible | changed: [3.110.101.30]
2024-07-24 09:16:20,006 p=771098 u=core n=ansible | changed: [13.201.185.232]
2024-07-24 09:16:20,023 p=771098 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:16:24,575 p=771098 u=core n=ansible | ok: [3.110.101.30]
2024-07-24 09:16:24,714 p=771098 u=core n=ansible | ok: [13.201.185.232]
2024-07-24 09:16:24,760 p=771098 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:16:24,761 p=771098 u=core n=ansible | 13.201.185.232             : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
2024-07-24 09:16:24,761 p=771098 u=core n=ansible | 3.110.101.30               : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
2024-07-24 09:22:14,036 p=772686 u=core n=ansible | PLAY [dev] ******************************************************************************************
2024-07-24 09:22:14,047 p=772686 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:22:22,490 p=772686 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:22:22,511 p=772686 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:22:26,071 p=772686 u=core n=ansible | changed: [35.154.202.43]
2024-07-24 09:22:26,085 p=772686 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:22:26,114 p=772686 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:22:26,128 p=772686 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:22:30,432 p=772686 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2024-07-24 09:22:30,435 p=772686 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:22:30,437 p=772686 u=core n=ansible | 35.154.202.43              : ok=2    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2024-07-24 09:25:22,510 p=773430 u=core n=ansible | PLAY [dev] ******************************************************************************************
2024-07-24 09:25:22,521 p=773430 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:25:30,804 p=773430 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:25:30,827 p=773430 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:25:34,512 p=773430 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:25:34,529 p=773430 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:25:34,562 p=773430 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:25:34,574 p=773430 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:25:38,916 p=773430 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2024-07-24 09:25:38,922 p=773430 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:25:38,923 p=773430 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2024-07-24 09:30:42,286 p=774654 u=core n=ansible | PLAY [dev] ******************************************************************************************
2024-07-24 09:30:42,299 p=774654 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:30:50,688 p=774654 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:30:50,711 p=774654 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:30:54,306 p=774654 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:30:54,323 p=774654 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:30:54,350 p=774654 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:30:54,361 p=774654 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:30:54,388 p=774654 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:30:54,417 p=774654 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:30:54,417 p=774654 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
2024-07-24 09:32:46,203 p=775117 u=core n=ansible | PLAY [dev] ******************************************************************************************
2024-07-24 09:32:46,215 p=775117 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:32:54,332 p=775117 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:32:54,356 p=775117 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:32:58,113 p=775117 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:32:58,126 p=775117 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:32:58,157 p=775117 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:32:58,170 p=775117 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:32:58,203 p=775117 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"msg": "The conditional check 'installed.succeeded' failed. The error was: error while evaluating conditional (installed.succeeded): 'dict object' has no attribute 'succeeded'\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: starting apache2\n  ^ here\n"}
2024-07-24 09:32:58,207 p=775117 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:32:58,207 p=775117 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2024-07-24 09:35:20,967 p=775730 u=core n=ansible | PLAY [dev] ******************************************************************************************
2024-07-24 09:35:20,978 p=775730 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:35:29,081 p=775730 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:35:29,101 p=775730 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:35:32,695 p=775730 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:35:32,710 p=775730 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:35:32,740 p=775730 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:35:32,752 p=775730 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:35:37,022 p=775730 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2024-07-24 09:35:37,026 p=775730 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:35:37,027 p=775730 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2024-07-24 09:38:07,436 p=776358 u=core n=ansible | PLAY [dev] ******************************************************************************************
2024-07-24 09:38:07,446 p=776358 u=core n=ansible | TASK [Gathering Facts] ******************************************************************************
2024-07-24 09:38:15,567 p=776358 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:38:15,590 p=776358 u=core n=ansible | TASK [apache-installation : check if nginx is installed] ********************************************
2024-07-24 09:38:19,412 p=776358 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 09:38:19,427 p=776358 u=core n=ansible | TASK [apache-installation : updating cache and installing apache2] **********************************
2024-07-24 09:38:19,456 p=776358 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:38:19,471 p=776358 u=core n=ansible | TASK [apache-installation : starting apache2] *******************************************************
2024-07-24 09:38:19,496 p=776358 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 09:38:19,528 p=776358 u=core n=ansible | PLAY RECAP ******************************************************************************************
2024-07-24 09:38:19,528 p=776358 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
2024-07-24 09:44:35,557 p=777914 u=core n=ansible | 35.154.202.43 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "172.31.40.209"
        ],
        "ansible_all_ipv6_addresses": [
            "fe80::37:d9ff:fec3:c4cd"
        ],
        "ansible_apparmor": {
            "status": "enabled"
        },
        "ansible_architecture": "x86_64",
        "ansible_bios_date": "10/16/2017",
        "ansible_bios_vendor": "Amazon EC2",
        "ansible_bios_version": "1.0",
        "ansible_board_asset_tag": "i-0ac7f80cd299d607d",
        "ansible_board_name": "NA",
        "ansible_board_serial": "NA",
        "ansible_board_vendor": "Amazon EC2",
        "ansible_board_version": "NA",
        "ansible_chassis_asset_tag": "Amazon EC2",
        "ansible_chassis_serial": "NA",
        "ansible_chassis_vendor": "Amazon EC2",
        "ansible_chassis_version": "NA",
        "ansible_cmdline": {
            "BOOT_IMAGE": "/vmlinuz-6.8.0-1009-aws",
            "console": "ttyS0",
            "nvme_core.io_timeout": "4294967295",
            "panic": "-1",
            "ro": true,
            "root": "PARTUUID=36fb1e15-9769-4fb8-9e5e-5f8e96d9a585"
        },
        "ansible_date_time": {
            "date": "2024-07-24",
            "day": "24",
            "epoch": "1721814274",
            "epoch_int": "1721814274",
            "hour": "09",
            "iso8601": "2024-07-24T09:44:34Z",
            "iso8601_basic": "20240724T094434614197",
            "iso8601_basic_short": "20240724T094434",
            "iso8601_micro": "2024-07-24T09:44:34.614197Z",
            "minute": "44",
            "month": "07",
            "second": "34",
            "time": "09:44:34",
            "tz": "UTC",
            "tz_dst": "UTC",
            "tz_offset": "+0000",
            "weekday": "Wednesday",
            "weekday_number": "3",
            "weeknumber": "30",
            "year": "2024"
        },
        "ansible_default_ipv4": {
            "address": "172.31.40.209",
            "alias": "ens5",
            "broadcast": "",
            "gateway": "172.31.32.1",
            "interface": "ens5",
            "macaddress": "02:37:d9:c3:c4:cd",
            "mtu": 9001,
            "netmask": "255.255.240.0",
            "network": "172.31.32.0",
            "type": "ether"
        },
        "ansible_default_ipv6": {},
        "ansible_device_links": {
            "ids": {
                "nvme0n1": [
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef",
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1",
                    "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001"
                ],
                "nvme0n1p1": [
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part1",
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part1",
                    "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part1"
                ],
                "nvme0n1p14": [
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part14",
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part14",
                    "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part14"
                ],
                "nvme0n1p15": [
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part15",
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part15",
                    "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part15"
                ],
                "nvme0n1p16": [
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part16",
                    "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part16",
                    "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part16"
                ]
            },
            "labels": {
                "nvme0n1p1": [
                    "cloudimg-rootfs"
                ],
                "nvme0n1p15": [
                    "UEFI"
                ],
                "nvme0n1p16": [
                    "BOOT"
                ]
            },
            "masters": {},
            "uuids": {
                "nvme0n1p1": [
                    "e97ae3ba-1e02-4d97-9427-d5f37ff742a9"
                ],
                "nvme0n1p15": [
                    "349B-1BE8"
                ],
                "nvme0n1p16": [
                    "9df3be1d-f619-4991-af0c-2c556f66595f"
                ]
            }
        },
        "ansible_devices": {
            "loop0": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "0",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "51688",
                "sectorsize": "512",
                "size": "25.24 MB",
                "support_discard": "4096",
                "vendor": null,
                "virtual": 1
            },
            "loop1": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "0",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "79520",
                "sectorsize": "512",
                "size": "38.83 MB",
                "support_discard": "4096",
                "vendor": null,
                "virtual": 1
            },
            "loop2": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "0",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "113992",
                "sectorsize": "512",
                "size": "55.66 MB",
                "support_discard": "4096",
                "vendor": null,
                "virtual": 1
            },
            "loop3": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "0",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "0",
                "sectorsize": "512",
                "size": "0.00 Bytes",
                "support_discard": "4096",
                "vendor": null,
                "virtual": 1
            },
            "loop4": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "1",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "0",
                "sectorsize": "512",
                "size": "0.00 Bytes",
                "support_discard": "512",
                "vendor": null,
                "virtual": 1
            },
            "loop5": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "1",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "0",
                "sectorsize": "512",
                "size": "0.00 Bytes",
                "support_discard": "512",
                "vendor": null,
                "virtual": 1
            },
            "loop6": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "1",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "0",
                "sectorsize": "512",
                "size": "0.00 Bytes",
                "support_discard": "512",
                "vendor": null,
                "virtual": 1
            },
            "loop7": {
                "holders": [],
                "host": "",
                "links": {
                    "ids": [],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "1",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "0",
                "sectorsize": "512",
                "size": "0.00 Bytes",
                "support_discard": "512",
                "vendor": null,
                "virtual": 1
            },
            "nvme0n1": {
                "holders": [],
                "host": "Non-Volatile memory controller: Amazon.com, Inc. NVMe EBS Controller",
                "links": {
                    "ids": [
                        "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef",
                        "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1",
                        "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001"
                    ],
                    "labels": [],
                    "masters": [],
                    "uuids": []
                },
                "model": "Amazon Elastic Block Store",
                "partitions": {
                    "nvme0n1p1": {
                        "holders": [],
                        "links": {
                            "ids": [
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part1",
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part1",
                                "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part1"
                            ],
                            "labels": [
                                "cloudimg-rootfs"
                            ],
                            "masters": [],
                            "uuids": [
                                "e97ae3ba-1e02-4d97-9427-d5f37ff742a9"
                            ]
                        },
                        "sectors": "14677983",
                        "sectorsize": 512,
                        "size": "7.00 GB",
                        "start": "2099200",
                        "uuid": "e97ae3ba-1e02-4d97-9427-d5f37ff742a9"
                    },
                    "nvme0n1p14": {
                        "holders": [],
                        "links": {
                            "ids": [
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part14",
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part14",
                                "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part14"
                            ],
                            "labels": [],
                            "masters": [],
                            "uuids": []
                        },
                        "sectors": "8192",
                        "sectorsize": 512,
                        "size": "4.00 MB",
                        "start": "2048",
                        "uuid": null
                    },
                    "nvme0n1p15": {
                        "holders": [],
                        "links": {
                            "ids": [
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part15",
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part15",
                                "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part15"
                            ],
                            "labels": [
                                "UEFI"
                            ],
                            "masters": [],
                            "uuids": [
                                "349B-1BE8"
                            ]
                        },
                        "sectors": "217088",
                        "sectorsize": 512,
                        "size": "106.00 MB",
                        "start": "10240",
                        "uuid": "349B-1BE8"
                    },
                    "nvme0n1p16": {
                        "holders": [],
                        "links": {
                            "ids": [
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef-part16",
                                "nvme-Amazon_Elastic_Block_Store_vol096b6c4e76b9b4fef_1-part16",
                                "nvme-nvme.1d0f-766f6c3039366236633465373662396234666566-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part16"
                            ],
                            "labels": [
                                "BOOT"
                            ],
                            "masters": [],
                            "uuids": [
                                "9df3be1d-f619-4991-af0c-2c556f66595f"
                            ]
                        },
                        "sectors": "1869825",
                        "sectorsize": 512,
                        "size": "913.00 MB",
                        "start": "227328",
                        "uuid": "9df3be1d-f619-4991-af0c-2c556f66595f"
                    }
                },
                "removable": "0",
                "rotational": "0",
                "sas_address": null,
                "sas_device_handle": null,
                "scheduler_mode": "none",
                "sectors": "16777216",
                "sectorsize": "512",
                "size": "8.00 GB",
                "support_discard": "512",
                "vendor": null,
                "virtual": 1
            }
        },
        "ansible_distribution": "Ubuntu",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Debian",
        "ansible_distribution_major_version": "24",
        "ansible_distribution_release": "noble",
        "ansible_distribution_version": "24.04",
        "ansible_dns": {
            "nameservers": [
                "127.0.0.53"
            ],
            "options": {
                "edns0": true,
                "trust-ad": true
            },
            "search": [
                "ap-south-1.compute.internal"
            ]
        },
        "ansible_domain": "ap-south-1.compute.internal",
        "ansible_effective_group_id": 1000,
        "ansible_effective_user_id": 1000,
        "ansible_ens5": {
            "active": true,
            "device": "ens5",
            "features": {
                "esp_hw_offload": "off [fixed]",
                "esp_tx_csum_hw_offload": "off [fixed]",
                "fcoe_mtu": "off [fixed]",
                "generic_receive_offload": "on",
                "generic_segmentation_offload": "on",
                "highdma": "on",
                "hsr_dup_offload": "off [fixed]",
                "hsr_fwd_offload": "off [fixed]",
                "hsr_tag_ins_offload": "off [fixed]",
                "hsr_tag_rm_offload": "off [fixed]",
                "hw_tc_offload": "off [fixed]",
                "l2_fwd_offload": "off [fixed]",
                "large_receive_offload": "off [fixed]",
                "loopback": "off [fixed]",
                "macsec_hw_offload": "off [fixed]",
                "netns_local": "off [fixed]",
                "ntuple_filters": "off [fixed]",
                "receive_hashing": "on",
                "rx_all": "off [fixed]",
                "rx_checksumming": "off [fixed]",
                "rx_fcs": "off [fixed]",
                "rx_gro_hw": "off [fixed]",
                "rx_gro_list": "off",
                "rx_udp_gro_forwarding": "off",
                "rx_udp_tunnel_port_offload": "off [fixed]",
                "rx_vlan_filter": "off [fixed]",
                "rx_vlan_offload": "off [fixed]",
                "rx_vlan_stag_filter": "off [fixed]",
                "rx_vlan_stag_hw_parse": "off [fixed]",
                "scatter_gather": "on",
                "tcp_segmentation_offload": "off",
                "tls_hw_record": "off [fixed]",
                "tls_hw_rx_offload": "off [fixed]",
                "tls_hw_tx_offload": "off [fixed]",
                "tx_checksum_fcoe_crc": "off [fixed]",
                "tx_checksum_ip_generic": "off [fixed]",
                "tx_checksum_ipv4": "on",
                "tx_checksum_ipv6": "off [fixed]",
                "tx_checksum_sctp": "off [fixed]",
                "tx_checksumming": "on",
                "tx_esp_segmentation": "off [fixed]",
                "tx_fcoe_segmentation": "off [fixed]",
                "tx_gre_csum_segmentation": "off [fixed]",
                "tx_gre_segmentation": "off [fixed]",
                "tx_gso_list": "off [fixed]",
                "tx_gso_partial": "off [fixed]",
                "tx_gso_robust": "off [fixed]",
                "tx_ipxip4_segmentation": "off [fixed]",
                "tx_ipxip6_segmentation": "off [fixed]",
                "tx_lockless": "off [fixed]",
                "tx_nocache_copy": "off",
                "tx_scatter_gather": "on",
                "tx_scatter_gather_fraglist": "off [fixed]",
                "tx_sctp_segmentation": "off [fixed]",
                "tx_tcp6_segmentation": "off [fixed]",
                "tx_tcp_ecn_segmentation": "off [fixed]",
                "tx_tcp_mangleid_segmentation": "off [fixed]",
                "tx_tcp_segmentation": "off [fixed]",
                "tx_tunnel_remcsum_segmentation": "off [fixed]",
                "tx_udp_segmentation": "off [fixed]",
                "tx_udp_tnl_csum_segmentation": "off [fixed]",
                "tx_udp_tnl_segmentation": "off [fixed]",
                "tx_vlan_offload": "off [fixed]",
                "tx_vlan_stag_hw_insert": "off [fixed]",
                "vlan_challenged": "off [fixed]"
            },
            "hw_timestamp_filters": [],
            "ipv4": {
                "address": "172.31.40.209",
                "broadcast": "",
                "netmask": "255.255.240.0",
                "network": "172.31.32.0"
            },
            "ipv6": [
                {
                    "address": "fe80::37:d9ff:fec3:c4cd",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "02:37:d9:c3:c4:cd",
            "module": "ena",
            "mtu": 9001,
            "pciid": "0000:00:05.0",
            "promisc": false,
            "timestamping": [],
            "type": "ether"
        },
        "ansible_env": {
            "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
            "HOME": "/home/ubuntu",
            "LANG": "C.UTF-8",
            "LOGNAME": "ubuntu",
            "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
            "PWD": "/home/ubuntu",
            "SHELL": "/bin/bash",
            "SHLVL": "0",
            "SSH_CLIENT": "185.136.166.67 40160 22",
            "SSH_CONNECTION": "185.136.166.67 40160 172.31.40.209 22",
            "SSH_TTY": "/dev/pts/0",
            "TERM": "screen",
            "USER": "ubuntu",
            "XDG_RUNTIME_DIR": "/run/user/1000",
            "XDG_SESSION_CLASS": "user",
            "XDG_SESSION_ID": "42",
            "XDG_SESSION_TYPE": "tty",
            "_": "/bin/sh"
        },
        "ansible_fibre_channel_wwn": [],
        "ansible_fips": false,
        "ansible_form_factor": "Other",
        "ansible_fqdn": "ip-172-31-40-209.ap-south-1.compute.internal",
        "ansible_hostname": "ip-172-31-40-209",
        "ansible_hostnqn": "",
        "ansible_interfaces": [
            "lo",
            "ens5"
        ],
        "ansible_is_chroot": false,
        "ansible_iscsi_iqn": "",
        "ansible_kernel": "6.8.0-1009-aws",
        "ansible_kernel_version": "#9-Ubuntu SMP Fri May 17 14:39:23 UTC 2024",
        "ansible_lo": {
            "active": true,
            "device": "lo",
            "features": {
                "esp_hw_offload": "off [fixed]",
                "esp_tx_csum_hw_offload": "off [fixed]",
                "fcoe_mtu": "off [fixed]",
                "generic_receive_offload": "on",
                "generic_segmentation_offload": "on",
                "highdma": "on [fixed]",
                "hsr_dup_offload": "off [fixed]",
                "hsr_fwd_offload": "off [fixed]",
                "hsr_tag_ins_offload": "off [fixed]",
                "hsr_tag_rm_offload": "off [fixed]",
                "hw_tc_offload": "off [fixed]",
                "l2_fwd_offload": "off [fixed]",
                "large_receive_offload": "off [fixed]",
                "loopback": "on [fixed]",
                "macsec_hw_offload": "off [fixed]",
                "netns_local": "on [fixed]",
                "ntuple_filters": "off [fixed]",
                "receive_hashing": "off [fixed]",
                "rx_all": "off [fixed]",
                "rx_checksumming": "on [fixed]",
                "rx_fcs": "off [fixed]",
                "rx_gro_hw": "off [fixed]",
                "rx_gro_list": "off",
                "rx_udp_gro_forwarding": "off",
                "rx_udp_tunnel_port_offload": "off [fixed]",
                "rx_vlan_filter": "off [fixed]",
                "rx_vlan_offload": "off [fixed]",
                "rx_vlan_stag_filter": "off [fixed]",
                "rx_vlan_stag_hw_parse": "off [fixed]",
                "scatter_gather": "on",
                "tcp_segmentation_offload": "on",
                "tls_hw_record": "off [fixed]",
                "tls_hw_rx_offload": "off [fixed]",
                "tls_hw_tx_offload": "off [fixed]",
                "tx_checksum_fcoe_crc": "off [fixed]",
                "tx_checksum_ip_generic": "on [fixed]",
                "tx_checksum_ipv4": "off [fixed]",
                "tx_checksum_ipv6": "off [fixed]",
                "tx_checksum_sctp": "on [fixed]",
                "tx_checksumming": "on",
                "tx_esp_segmentation": "off [fixed]",
                "tx_fcoe_segmentation": "off [fixed]",
                "tx_gre_csum_segmentation": "off [fixed]",
                "tx_gre_segmentation": "off [fixed]",
                "tx_gso_list": "on",
                "tx_gso_partial": "off [fixed]",
                "tx_gso_robust": "off [fixed]",
                "tx_ipxip4_segmentation": "off [fixed]",
                "tx_ipxip6_segmentation": "off [fixed]",
                "tx_lockless": "on [fixed]",
                "tx_nocache_copy": "off [fixed]",
                "tx_scatter_gather": "on [fixed]",
                "tx_scatter_gather_fraglist": "on [fixed]",
                "tx_sctp_segmentation": "on",
                "tx_tcp6_segmentation": "on",
                "tx_tcp_ecn_segmentation": "on",
                "tx_tcp_mangleid_segmentation": "on",
                "tx_tcp_segmentation": "on",
                "tx_tunnel_remcsum_segmentation": "off [fixed]",
                "tx_udp_segmentation": "on",
                "tx_udp_tnl_csum_segmentation": "off [fixed]",
                "tx_udp_tnl_segmentation": "off [fixed]",
                "tx_vlan_offload": "off [fixed]",
                "tx_vlan_stag_hw_insert": "off [fixed]",
                "vlan_challenged": "on [fixed]"
            },
            "hw_timestamp_filters": [],
            "ipv4": {
                "address": "127.0.0.1",
                "broadcast": "",
                "netmask": "255.0.0.0",
                "network": "127.0.0.0"
            },
            "ipv6": [
                {
                    "address": "::1",
                    "prefix": "128",
                    "scope": "host"
                }
            ],
            "mtu": 65536,
            "promisc": false,
            "timestamping": [],
            "type": "loopback"
        },
        "ansible_local": {},
        "ansible_lsb": {
            "codename": "noble",
            "description": "Ubuntu 24.04 LTS",
            "id": "Ubuntu",
            "major_release": "24",
            "release": "24.04"
        },
        "ansible_machine": "x86_64",
        "ansible_machine_id": "ec255eb2f4e7d69144cd40ba9b890800",
        "ansible_memfree_mb": 15,
        "ansible_memory_mb": {
            "nocache": {
                "free": 121,
                "used": 297
            },
            "real": {
                "free": 15,
                "total": 418,
                "used": 403
            },
            "swap": {
                "cached": 0,
                "free": 0,
                "total": 0,
                "used": 0
            }
        },
        "ansible_memtotal_mb": 418,
        "ansible_mounts": [
            {
                "block_available": 1297874,
                "block_size": 4096,
                "block_total": 1758594,
                "block_used": 460720,
                "device": "/dev/root",
                "fstype": "ext4",
                "inode_available": 839337,
                "inode_total": 917504,
                "inode_used": 78167,
                "mount": "/",
                "options": "rw,relatime,discard,errors=remount-ro,commit=30",
                "size_available": 5316091904,
                "size_total": 7203201024,
                "uuid": "e97ae3ba-1e02-4d97-9427-d5f37ff742a9"
            },
            {
                "block_available": 0,
                "block_size": 131072,
                "block_total": 202,
                "block_used": 202,
                "device": "/dev/loop0",
                "fstype": "squashfs",
                "inode_available": 0,
                "inode_total": 16,
                "inode_used": 16,
                "mount": "/snap/amazon-ssm-agent/7993",
                "options": "ro,nodev,relatime,errors=continue,threads=single",
                "size_available": 0,
                "size_total": 26476544,
                "uuid": "N/A"
            },
            {
                "block_available": 0,
                "block_size": 131072,
                "block_total": 446,
                "block_used": 446,
                "device": "/dev/loop2",
                "fstype": "squashfs",
                "inode_available": 0,
                "inode_total": 10944,
                "inode_used": 10944,
                "mount": "/snap/core18/2829",
                "options": "ro,nodev,relatime,errors=continue,threads=single",
                "size_available": 0,
                "size_total": 58458112,
                "uuid": "N/A"
            },
            {
                "block_available": 0,
                "block_size": 131072,
                "block_total": 311,
                "block_used": 311,
                "device": "/dev/loop1",
                "fstype": "squashfs",
                "inode_available": 0,
                "inode_total": 651,
                "inode_used": 651,
                "mount": "/snap/snapd/21759",
                "options": "ro,nodev,relatime,errors=continue,threads=single",
                "size_available": 0,
                "size_total": 40763392,
                "uuid": "N/A"
            },
            {
                "block_available": 190355,
                "block_size": 4096,
                "block_total": 225380,
                "block_used": 35025,
                "device": "/dev/nvme0n1p16",
                "fstype": "ext4",
                "inode_available": 57895,
                "inode_total": 58496,
                "inode_used": 601,
                "mount": "/boot",
                "options": "rw,relatime",
                "size_available": 779694080,
                "size_total": 923156480,
                "uuid": "9df3be1d-f619-4991-af0c-2c556f66595f"
            },
            {
                "block_available": 201172,
                "block_size": 512,
                "block_total": 213663,
                "block_used": 12491,
                "device": "/dev/nvme0n1p15",
                "fstype": "vfat",
                "inode_available": 0,
                "inode_total": 0,
                "inode_used": 0,
                "mount": "/boot/efi",
                "options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro",
                "size_available": 103000064,
                "size_total": 109395456,
                "uuid": "349B-1BE8"
            }
        ],
        "ansible_nodename": "ip-172-31-40-209",
        "ansible_os_family": "Debian",
        "ansible_pkg_mgr": "apt",
        "ansible_proc_cmdline": {
            "BOOT_IMAGE": "/vmlinuz-6.8.0-1009-aws",
            "console": [
                "tty1",
                "ttyS0"
            ],
            "nvme_core.io_timeout": "4294967295",
            "panic": "-1",
            "ro": true,
            "root": "PARTUUID=36fb1e15-9769-4fb8-9e5e-5f8e96d9a585"
        },
        "ansible_processor": [
            "0",
            "AuthenticAMD",
            "AMD EPYC 7571",
            "1",
            "AuthenticAMD",
            "AMD EPYC 7571"
        ],
        "ansible_processor_cores": 1,
        "ansible_processor_count": 1,
        "ansible_processor_nproc": 2,
        "ansible_processor_threads_per_core": 2,
        "ansible_processor_vcpus": 2,
        "ansible_product_name": "t3a.nano",
        "ansible_product_serial": "NA",
        "ansible_product_uuid": "NA",
        "ansible_product_version": "NA",
        "ansible_python": {
            "executable": "/usr/bin/python3",
            "has_sslcontext": true,
            "type": "cpython",
            "version": {
                "major": 3,
                "micro": 3,
                "minor": 12,
                "releaselevel": "final",
                "serial": 0
            },
            "version_info": [
                3,
                12,
                3,
                "final",
                0
            ]
        },
        "ansible_python_version": "3.12.3",
        "ansible_real_group_id": 1000,
        "ansible_real_user_id": 1000,
        "ansible_selinux": {
            "status": "disabled"
        },
        "ansible_selinux_python_present": true,
        "ansible_service_mgr": "systemd",
        "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBO1jsH3RLJlvtPQMgFVwk1DoMqlYNYQPWMw1hkyZChPYw0NAEnHYOW74F4Tx3RQmxS/O8kOCfU/zr5qDEn1HG+8=",
        "ansible_ssh_host_key_ecdsa_public_keytype": "ecdsa-sha2-nistp256",
        "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAINkApEpCYgLVqTQvzw/HXdw/cqT9fPzreR4nD3W8BYJI",
        "ansible_ssh_host_key_ed25519_public_keytype": "ssh-ed25519",
        "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABgQCpxqCnKQHSUvKoLgcFyrwMwBmePTouHHBe9Ngsn6eiz7JOZ1XLETMRDQMDbjZ+xXi0Nc5WLC6wi77YYVzoPkyQ7s1O/GuC/semdKLaXuCLnxgcDkWxVCS4MeQZiStXGOXR8NuMAlmV4Rdr1RTY4cWQntGb+/26DmFZbydj7DxTE8ZcB7l0/kEwn6485m4670nD9E0a4Q9LygTiV9md8dHRYvVc3Eza5X04SSSGfBbWEfFCcA1arp7Ot1PC5g7VY0GPWBT3Xb7R35J4HT19Dlt7iytwGG8yct6V0vrH8aWgzOz3KSGG+VPbeKqSe2OJrSS3UnVEoeh9z2BBhEOpQoiMkQ5CylOsbxm7+1viost3PSROvPWpN4HqnpyPEYIgnXMiaoERXxS87e8rGhWXswEI3TEWA8K8npARNoOQehlKVithp7H3X+IgC+CdInXfKaMCNmsgCXF7psuf4ZegF/B7fjg0B+Ndmtgn23qszRK7LRmCu5U+0J7UNl7DqKgkMIU=",
        "ansible_ssh_host_key_rsa_public_keytype": "ssh-rsa",
        "ansible_swapfree_mb": 0,
        "ansible_swaptotal_mb": 0,
        "ansible_system": "Linux",
        "ansible_system_capabilities": [
            ""
        ],
        "ansible_system_capabilities_enforced": "True",
        "ansible_system_vendor": "Amazon EC2",
        "ansible_uptime_seconds": 12323,
        "ansible_user_dir": "/home/ubuntu",
        "ansible_user_gecos": "Ubuntu",
        "ansible_user_gid": 1000,
        "ansible_user_id": "ubuntu",
        "ansible_user_shell": "/bin/bash",
        "ansible_user_uid": 1000,
        "ansible_userspace_architecture": "x86_64",
        "ansible_userspace_bits": "64",
        "ansible_virtualization_role": "guest",
        "ansible_virtualization_tech_guest": [
            "kvm"
        ],
        "ansible_virtualization_tech_host": [],
        "ansible_virtualization_type": "kvm",
        "discovered_interpreter_python": "/usr/bin/python3",
        "gather_subset": [
            "all"
        ],
        "module_setup": true
    },
    "changed": false,
    "deprecations": [],
    "warnings": []
}
2024-07-24 10:24:30,736 p=786795 u=core n=ansible | playbook: playbooks/role.yml
2024-07-24 10:24:30,736 p=786795 u=core n=ansible |   play #1 (dev): dev	TAGS: []
2024-07-24 10:24:30,738 p=786795 u=core n=ansible |       TASK TAGS: []

2024-07-24 11:17:30,983 p=798561 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:17:30,994 p=798561 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:17:35,351 p=798561 u=core n=ansible | fatal: [13.201.46.129]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '13.201.46.129' (ED25519) to the list of known hosts.\r\nubuntu@13.201.46.129: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", "unreachable": true}
2024-07-24 11:17:39,176 p=798561 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:18:04,786 p=798561 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-24 11:18:16,410 p=798740 u=core n=ansible | 13.201.46.129 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@13.201.46.129: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2024-07-24 11:18:19,522 p=798740 u=core n=ansible | 35.154.202.43 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 11:18:48,239 p=798740 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-24 11:18:54,268 p=798892 u=core n=ansible | 13.201.46.129 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@13.201.46.129: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2024-07-24 11:18:56,779 p=798892 u=core n=ansible | 43.205.206.239 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '43.205.206.239' (ED25519) to the list of known hosts.\r\nubuntu@43.205.206.239: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2024-07-24 11:18:57,355 p=798892 u=core n=ansible | 35.154.202.43 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 11:19:56,972 p=799130 u=core n=ansible | 35.154.202.43 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 11:19:58,226 p=799130 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:19:58,227 p=799130 u=core n=ansible | 13.201.46.129 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 11:19:58,614 p=799130 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:19:58,614 p=799130 u=core n=ansible | 43.205.206.239 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-24 11:20:47,338 p=799431 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:20:47,349 p=799431 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:20:52,978 p=799431 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:20:53,025 p=799431 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:20:53,026 p=799431 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:20:53,048 p=799431 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:20:53,049 p=799431 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:20:53,075 p=799431 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:20:56,693 p=799431 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:20:56,700 p=799431 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.005446", "end": "2024-07-24 11:20:56.288005", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:20:56.282559", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:20:56,701 p=799431 u=core n=ansible | ...ignoring
2024-07-24 11:20:56,727 p=799431 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.006989", "end": "2024-07-24 11:20:56.296035", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:20:56.289046", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:20:56,728 p=799431 u=core n=ansible | ...ignoring
2024-07-24 11:20:56,742 p=799431 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-24 11:21:00,571 p=799431 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (dnf) module: register, when. Supported parameters include: disable_excludes, update_cache (expire-cache), allowerasing, cacheonly, download_only, install_repoquery, disable_plugin, security, autoremove, nobest, disable_gpg_check, allow_downgrade, list, state, install_weak_deps, releasever, name (pkg), enable_plugin, disablerepo, download_dir, enablerepo, validate_certs, update_only, skip_broken, lock_timeout, conf_file, exclude, installroot, bugfix."}
2024-07-24 11:21:00,659 p=799431 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (dnf) module: register, when. Supported parameters include: name (pkg), update_only, disablerepo, disable_excludes, state, enable_plugin, releasever, nobest, conf_file, skip_broken, lock_timeout, installroot, exclude, security, install_weak_deps, autoremove, bugfix, update_cache (expire-cache), cacheonly, disable_gpg_check, disable_plugin, download_dir, install_repoquery, download_only, enablerepo, list, validate_certs, allowerasing, allow_downgrade."}
2024-07-24 11:21:00,809 p=799431 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (dnf) module: register, when. Supported parameters include: autoremove, update_only, installroot, lock_timeout, download_only, enable_plugin, disable_gpg_check, download_dir, bugfix, disablerepo, disable_plugin, state, allowerasing, install_repoquery, list, exclude, releasever, install_weak_deps, skip_broken, validate_certs, nobest, name (pkg), conf_file, disable_excludes, cacheonly, update_cache (expire-cache), allow_downgrade, security, enablerepo."}
2024-07-24 11:21:00,812 p=799431 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:21:00,812 p=799431 u=core n=ansible | 13.201.46.129              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:21:00,812 p=799431 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 11:21:00,813 p=799431 u=core n=ansible | 43.205.206.239             : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:22:40,938 p=799934 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:22:40,957 p=799934 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:22:48,113 p=799934 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:22:48,114 p=799934 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:22:48,202 p=799934 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:22:48,203 p=799934 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:22:48,931 p=799934 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:22:48,954 p=799934 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:22:52,622 p=799934 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004389", "end": "2024-07-24 11:22:52.198102", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:22:52.193713", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:22:52,623 p=799934 u=core n=ansible | ...ignoring
2024-07-24 11:22:52,668 p=799934 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004929", "end": "2024-07-24 11:22:52.245133", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:22:52.240204", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:22:52,668 p=799934 u=core n=ansible | ...ignoring
2024-07-24 11:22:52,681 p=799934 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:22:52,693 p=799934 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-24 11:22:56,424 p=799934 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'installed-2'"}
2024-07-24 11:22:56,537 p=799934 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'installed-2'"}
2024-07-24 11:22:56,577 p=799934 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'installed-2'"}
2024-07-24 11:22:56,581 p=799934 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:22:56,582 p=799934 u=core n=ansible | 13.201.46.129              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:22:56,582 p=799934 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-24 11:22:56,586 p=799934 u=core n=ansible | 43.205.206.239             : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:25:28,425 p=800671 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:25:28,437 p=800671 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:25:35,592 p=800671 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:25:35,593 p=800671 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:25:35,755 p=800671 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:25:35,755 p=800671 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:25:35,968 p=800671 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:25:36,000 p=800671 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:25:39,609 p=800671 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:25:39,637 p=800671 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004870", "end": "2024-07-24 11:25:39.225624", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:25:39.220754", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:25:39,637 p=800671 u=core n=ansible | ...ignoring
2024-07-24 11:25:39,662 p=800671 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004576", "end": "2024-07-24 11:25:39.250282", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:25:39.245706", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:25:39,662 p=800671 u=core n=ansible | ...ignoring
2024-07-24 11:25:39,679 p=800671 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-24 11:25:39,727 p=800671 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:25:49,843 p=800671 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'installed-2'"}
2024-07-24 11:25:50,966 p=800671 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'installed-2'"}
2024-07-24 11:25:50,983 p=800671 u=core n=ansible | TASK [apache-installation-v2 : starting httpd] *****************************************************
2024-07-24 11:25:51,013 p=800671 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"msg": "The conditional check 'installed-2.changed' failed. The error was: error while evaluating conditional (installed-2.changed): 'installed' is undefined\n\nThe error appears to be in '/home/core/Ansible/playbooks/roles/apache-installation-v2/tasks/main.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: starting httpd\n  ^ here\n"}
2024-07-24 11:25:51,018 p=800671 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:25:51,019 p=800671 u=core n=ansible | 13.201.46.129              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:25:51,019 p=800671 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2024-07-24 11:25:51,020 p=800671 u=core n=ansible | 43.205.206.239             : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:27:33,978 p=801223 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:27:33,988 p=801223 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:27:41,456 p=801223 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:27:41,528 p=801223 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:27:41,528 p=801223 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:27:41,584 p=801223 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:27:41,586 p=801223 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:27:41,608 p=801223 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:27:45,177 p=801223 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:27:45,268 p=801223 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.005857", "end": "2024-07-24 11:27:44.822854", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:27:44.816997", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:27:45,269 p=801223 u=core n=ansible | ...ignoring
2024-07-24 11:27:45,347 p=801223 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.007258", "end": "2024-07-24 11:27:44.919526", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:27:44.912268", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:27:45,347 p=801223 u=core n=ansible | ...ignoring
2024-07-24 11:27:45,362 p=801223 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-24 11:27:45,390 p=801223 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:27:51,690 p=801223 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:27:51,917 p=801223 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:27:51,936 p=801223 u=core n=ansible | TASK [apache-installation-v2 : starting httpd] *****************************************************
2024-07-24 11:27:51,981 p=801223 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:27:51,985 p=801223 u=core n=ansible | skipping: [13.201.46.129]
2024-07-24 11:27:52,002 p=801223 u=core n=ansible | skipping: [43.205.206.239]
2024-07-24 11:27:52,053 p=801223 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:27:52,054 p=801223 u=core n=ansible | 13.201.46.129              : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   
2024-07-24 11:27:52,054 p=801223 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
2024-07-24 11:27:52,054 p=801223 u=core n=ansible | 43.205.206.239             : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   
2024-07-24 11:34:17,567 p=802796 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:34:17,580 p=802796 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:34:24,842 p=802796 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:34:24,842 p=802796 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:34:24,869 p=802796 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:34:24,871 p=802796 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:34:25,274 p=802796 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:34:25,301 p=802796 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:34:28,997 p=802796 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.007579", "end": "2024-07-24 11:34:28.573869", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:34:28.566290", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:34:28,998 p=802796 u=core n=ansible | ...ignoring
2024-07-24 11:34:29,014 p=802796 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:34:29,025 p=802796 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.006017", "end": "2024-07-24 11:34:28.601590", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:34:28.595573", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:34:29,025 p=802796 u=core n=ansible | ...ignoring
2024-07-24 11:34:29,039 p=802796 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-24 11:34:29,091 p=802796 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:34:35,200 p=802796 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:34:35,473 p=802796 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:34:35,490 p=802796 u=core n=ansible | TASK [apache-installation-v2 : starting httpd] *****************************************************
2024-07-24 11:34:35,537 p=802796 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:34:35,541 p=802796 u=core n=ansible | skipping: [13.201.46.129]
2024-07-24 11:34:35,557 p=802796 u=core n=ansible | skipping: [43.205.206.239]
2024-07-24 11:34:35,604 p=802796 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:34:35,604 p=802796 u=core n=ansible | 13.201.46.129              : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   
2024-07-24 11:34:35,604 p=802796 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
2024-07-24 11:34:35,605 p=802796 u=core n=ansible | 43.205.206.239             : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   
2024-07-24 11:34:50,777 p=803012 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:34:50,797 p=803012 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:34:56,337 p=803012 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:34:56,338 p=803012 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:34:56,362 p=803012 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:34:56,362 p=803012 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:34:56,491 p=803012 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:34:56,511 p=803012 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:35:00,111 p=803012 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:35:00,208 p=803012 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.006392", "end": "2024-07-24 11:34:59.769730", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:34:59.763338", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:35:00,208 p=803012 u=core n=ansible | ...ignoring
2024-07-24 11:35:00,211 p=803012 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004497", "end": "2024-07-24 11:34:59.781710", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:34:59.777213", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:35:00,211 p=803012 u=core n=ansible | ...ignoring
2024-07-24 11:35:00,224 p=803012 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing apache2] ******************************
2024-07-24 11:35:00,270 p=803012 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:35:04,250 p=803012 u=core n=ansible | [WARNING]: Updating cache and auto-installing missing dependency: python3-apt

2024-07-24 11:35:04,250 p=803012 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 11:35:04,464 p=803012 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 11:35:04,483 p=803012 u=core n=ansible | TASK [apache-installation-v2 : starting apache2] ***************************************************
2024-07-24 11:35:04,514 p=803012 u=core n=ansible | skipping: [35.154.202.43]
2024-07-24 11:35:04,547 p=803012 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:35:04,548 p=803012 u=core n=ansible | 13.201.46.129              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:35:04,549 p=803012 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
2024-07-24 11:35:04,550 p=803012 u=core n=ansible | 43.205.206.239             : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:37:33,219 p=803722 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:37:33,230 p=803722 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:37:40,504 p=803722 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:37:40,505 p=803722 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:37:40,554 p=803722 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:37:40,554 p=803722 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:37:41,132 p=803722 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:37:41,155 p=803722 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:37:44,722 p=803722 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.007113", "end": "2024-07-24 11:37:44.322371", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:37:44.315258", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 11:37:44,723 p=803722 u=core n=ansible | ...ignoring
2024-07-24 11:37:44,816 p=803722 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004574", "end": "2024-07-24 11:37:44.390218", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:37:44.385644", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:37:44,816 p=803722 u=core n=ansible | ...ignoring
2024-07-24 11:37:44,901 p=803722 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.005178", "end": "2024-07-24 11:37:44.482730", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:37:44.477552", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:37:44,902 p=803722 u=core n=ansible | ...ignoring
2024-07-24 11:37:44,920 p=803722 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing apache2] ******************************
2024-07-24 11:37:48,750 p=803722 u=core n=ansible | [WARNING]: Updating cache and auto-installing missing dependency: python3-apt

2024-07-24 11:37:48,752 p=803722 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 11:37:48,764 p=803722 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 11:38:25,666 p=803722 u=core n=ansible | changed: [35.154.202.43]
2024-07-24 11:38:25,681 p=803722 u=core n=ansible | TASK [apache-installation-v2 : starting apache2] ***************************************************
2024-07-24 11:38:30,290 p=803722 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:38:30,329 p=803722 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:38:30,329 p=803722 u=core n=ansible | 13.201.46.129              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:38:30,330 p=803722 u=core n=ansible | 35.154.202.43              : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
2024-07-24 11:38:30,330 p=803722 u=core n=ansible | 43.205.206.239             : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:42:20,645 p=804894 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-24 11:42:20,655 p=804894 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-24 11:42:27,881 p=804894 u=core n=ansible | [WARNING]: Platform linux on host 43.205.206.239 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:42:27,881 p=804894 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:42:28,086 p=804894 u=core n=ansible | [WARNING]: Platform linux on host 13.201.46.129 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-24 11:42:28,086 p=804894 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:42:28,565 p=804894 u=core n=ansible | ok: [35.154.202.43]
2024-07-24 11:42:28,588 p=804894 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-24 11:42:32,176 p=804894 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.006061", "end": "2024-07-24 11:42:31.776716", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:42:31.770655", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-24 11:42:32,177 p=804894 u=core n=ansible | ...ignoring
2024-07-24 11:42:32,188 p=804894 u=core n=ansible | fatal: [43.205.206.239]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004426", "end": "2024-07-24 11:42:31.768647", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:42:31.764221", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:42:32,189 p=804894 u=core n=ansible | ...ignoring
2024-07-24 11:42:32,189 p=804894 u=core n=ansible | fatal: [13.201.46.129]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.005322", "end": "2024-07-24 11:42:31.773620", "msg": "non-zero return code", "rc": 1, "start": "2024-07-24 11:42:31.768298", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-24 11:42:32,189 p=804894 u=core n=ansible | ...ignoring
2024-07-24 11:42:32,202 p=804894 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-24 11:42:36,214 p=804894 u=core n=ansible | fatal: [35.154.202.43]: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python3 (3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
2024-07-24 11:42:38,108 p=804894 u=core n=ansible | ok: [43.205.206.239]
2024-07-24 11:42:38,418 p=804894 u=core n=ansible | ok: [13.201.46.129]
2024-07-24 11:42:38,430 p=804894 u=core n=ansible | TASK [apache-installation-v2 : starting httpd] *****************************************************
2024-07-24 11:42:38,465 p=804894 u=core n=ansible | skipping: [13.201.46.129]
2024-07-24 11:42:38,482 p=804894 u=core n=ansible | skipping: [43.205.206.239]
2024-07-24 11:42:38,525 p=804894 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-24 11:42:38,525 p=804894 u=core n=ansible | 13.201.46.129              : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   
2024-07-24 11:42:38,526 p=804894 u=core n=ansible | 35.154.202.43              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-24 11:42:38,526 p=804894 u=core n=ansible | 43.205.206.239             : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   
2024-07-25 05:23:40,115 p=1040255 u=core n=ansible | 3.110.158.18 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:23:59,052 p=1040349 u=core n=ansible | [WARNING]: Platform linux on host 3.6.41.146 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 05:23:59,054 p=1040349 u=core n=ansible | 3.6.41.146 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:24:27,660 p=1040349 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-25 05:25:31,642 p=1040709 u=core n=ansible | [WARNING]: Platform linux on host 3.6.41.146 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 05:25:31,643 p=1040709 u=core n=ansible | 3.6.41.146 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:25:31,918 p=1040709 u=core n=ansible | 3.110.158.18 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:25:36,170 p=1040709 u=core n=ansible | 65.0.107.56 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:26:00,022 p=1040879 u=core n=ansible | 65.0.107.56 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:26:00,081 p=1040879 u=core n=ansible | [WARNING]: Platform linux on host 3.6.41.146 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 05:26:00,081 p=1040879 u=core n=ansible | 3.6.41.146 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 05:31:37,078 p=1042172 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 05:31:37,091 p=1042172 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 05:31:44,338 p=1042172 u=core n=ansible | [WARNING]: Platform linux on host 3.6.41.146 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 05:31:44,338 p=1042172 u=core n=ansible | ok: [3.6.41.146]
2024-07-25 05:31:45,365 p=1042172 u=core n=ansible | ok: [65.0.107.56]
2024-07-25 05:31:45,387 p=1042172 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-25 05:31:48,945 p=1042172 u=core n=ansible | fatal: [65.0.107.56]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.006166", "end": "2024-07-25 05:31:48.555241", "msg": "non-zero return code", "rc": 1, "start": "2024-07-25 05:31:48.549075", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-25 05:31:48,946 p=1042172 u=core n=ansible | ...ignoring
2024-07-25 05:31:49,051 p=1042172 u=core n=ansible | fatal: [3.6.41.146]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.006306", "end": "2024-07-25 05:31:48.637620", "msg": "non-zero return code", "rc": 1, "start": "2024-07-25 05:31:48.631314", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-25 05:31:49,051 p=1042172 u=core n=ansible | ...ignoring
2024-07-25 05:31:49,068 p=1042172 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing apache2] ******************************
2024-07-25 05:31:53,102 p=1042172 u=core n=ansible | [WARNING]: Updating cache and auto-installing missing dependency: python3-apt

2024-07-25 05:31:53,103 p=1042172 u=core n=ansible | fatal: [3.6.41.146]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-25 05:32:34,868 p=1042172 u=core n=ansible | changed: [65.0.107.56]
2024-07-25 05:32:34,883 p=1042172 u=core n=ansible | TASK [apache-installation-v2 : starting apache2] ***************************************************
2024-07-25 05:32:39,402 p=1042172 u=core n=ansible | ok: [65.0.107.56]
2024-07-25 05:32:39,435 p=1042172 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 05:32:39,435 p=1042172 u=core n=ansible | 3.6.41.146                 : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-25 05:32:39,435 p=1042172 u=core n=ansible | 65.0.107.56                : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
2024-07-25 05:33:26,951 p=1042665 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 05:33:26,963 p=1042665 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 05:33:32,776 p=1042665 u=core n=ansible | ok: [65.0.107.56]
2024-07-25 05:33:33,746 p=1042665 u=core n=ansible | [WARNING]: Platform linux on host 3.6.41.146 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 05:33:33,747 p=1042665 u=core n=ansible | ok: [3.6.41.146]
2024-07-25 05:33:33,768 p=1042665 u=core n=ansible | TASK [apache-installation-v2 : check if nginx is installed] ****************************************
2024-07-25 05:33:37,269 p=1042665 u=core n=ansible | fatal: [3.6.41.146]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.004727", "end": "2024-07-25 05:33:36.859307", "msg": "non-zero return code", "rc": 1, "start": "2024-07-25 05:33:36.854580", "stderr": "which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)", "stderr_lines": ["which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)"], "stdout": "", "stdout_lines": []}
2024-07-25 05:33:37,270 p=1042665 u=core n=ansible | ...ignoring
2024-07-25 05:33:37,341 p=1042665 u=core n=ansible | fatal: [65.0.107.56]: FAILED! => {"changed": false, "cmd": ["which", "nginx"], "delta": "0:00:00.007226", "end": "2024-07-25 05:33:36.953432", "msg": "non-zero return code", "rc": 1, "start": "2024-07-25 05:33:36.946206", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-25 05:33:37,341 p=1042665 u=core n=ansible | ...ignoring
2024-07-25 05:33:37,365 p=1042665 u=core n=ansible | TASK [apache-installation-v2 : updating cache and installing httpd] ********************************
2024-07-25 05:33:41,423 p=1042665 u=core n=ansible | fatal: [65.0.107.56]: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python3 (3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
2024-07-25 05:33:47,047 p=1042665 u=core n=ansible | changed: [3.6.41.146]
2024-07-25 05:33:47,061 p=1042665 u=core n=ansible | TASK [apache-installation-v2 : starting httpd] *****************************************************
2024-07-25 05:33:52,499 p=1042665 u=core n=ansible | changed: [3.6.41.146]
2024-07-25 05:33:52,529 p=1042665 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 05:33:52,529 p=1042665 u=core n=ansible | 3.6.41.146                 : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
2024-07-25 05:33:52,529 p=1042665 u=core n=ansible | 65.0.107.56                : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
2024-07-25 06:45:35,035 p=1066021 u=core n=ansible | ERROR! couldn't resolve module/action 'synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/roles/copying-files/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Transfer file from ServerA to ServerB
  ^ here

2024-07-25 06:49:13,102 p=1066862 u=core n=ansible | ERROR! couldn't resolve module/action 'synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/roles/copying-files/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: test
  ^ here

2024-07-25 06:50:36,279 p=1067176 u=core n=ansible | ERROR! couldn't resolve module/action 'ansible.posix.synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/roles/copying-files/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: test
  ^ here

2024-07-25 06:51:15,085 p=1067305 u=core n=ansible | ERROR! couldn't resolve module/action 'ansible.posix.synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/roles/copying-files/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: test
  ^ here

2024-07-25 06:52:45,208 p=1067628 u=core n=ansible | ERROR! The requirements file '/home/core/Ansible/requirements.yml' does not exist.
2024-07-25 06:59:17,207 p=1069107 u=core n=ansible | ERROR! couldn't resolve module/action 'ansible.posix.synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/roles/copying-files/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: test
  ^ here

2024-07-25 07:03:23,704 p=1069983 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:03:23,705 p=1069983 u=core n=ansible | server3 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:03:24,323 p=1069983 u=core n=ansible | server1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:04:02,223 p=1069983 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-25 07:04:09,623 p=1070248 u=core n=ansible | server1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:04:09,742 p=1070248 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:04:09,743 p=1070248 u=core n=ansible | server3 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:04:16,948 p=1070248 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-25 07:04:54,776 p=1070371 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-25 07:06:13,982 p=1070740 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:06:13,983 p=1070740 u=core n=ansible | server3 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:06:19,572 p=1070740 u=core n=ansible | server2 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:06:47,610 p=1070890 u=core n=ansible | server1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:07:13,419 p=1071004 u=core n=ansible | server2 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:09:47,796 p=1071641 u=core n=ansible | ERROR! couldn't resolve module/action 'synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/copy.yml': line 3, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Transfer file from ServerA to ServerB
      ^ here

2024-07-25 07:15:57,908 p=1073014 u=core n=ansible | ERROR! couldn't resolve module/action 'synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/core/Ansible/playbooks/copy.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Transfer file from ServerA to ServerB
      ^ here

2024-07-25 07:17:13,836 p=1073282 u=core n=ansible | ERROR! - None of the provided paths were usable. Please specify a valid path with --collections-path
2024-07-25 07:17:59,050 p=1073448 u=core n=ansible | ERROR! - None of the provided paths were usable. Please specify a valid path with --collections-path
2024-07-25 07:18:32,104 p=1073569 u=core n=ansible | Starting galaxy collection install process
2024-07-25 07:18:32,104 p=1073569 u=core n=ansible | Process install dependency map
2024-07-25 07:18:32,105 p=1073569 u=core n=ansible | |
2024-07-25 07:18:32,207 p=1073569 u=core n=ansible | ERROR! Unexpected Exception, this is probably a bug: CollectionDependencyProvider.find_matches() got an unexpected keyword argument 'identifier'
2024-07-25 07:18:32,208 p=1073569 u=core n=ansible | to see the full traceback, use -vvv
2024-07-25 07:18:32,210 p=1073569 u=core n=ansible | the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 567, in run
    return context.CLIARGS['func']()
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 86, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 1201, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 1228, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3/dist-packages/ansible/galaxy/collection/__init__.py", line 513, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/usr/lib/python3/dist-packages/ansible/galaxy/collection/__init__.py", line 1327, in _resolve_depenency_map
    return collection_dep_resolver.resolve(
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 147, in _add_to_criteria
    matches = self._p.find_matches(
TypeError: CollectionDependencyProvider.find_matches() got an unexpected keyword argument 'identifier'

2024-07-25 07:18:44,297 p=1073637 u=root n=ansible | Starting galaxy collection install process
2024-07-25 07:18:44,298 p=1073637 u=root n=ansible | Process install dependency map
2024-07-25 07:18:44,299 p=1073637 u=root n=ansible | |
2024-07-25 07:18:44,400 p=1073637 u=root n=ansible | ERROR! Unexpected Exception, this is probably a bug: CollectionDependencyProvider.find_matches() got an unexpected keyword argument 'identifier'
2024-07-25 07:18:44,401 p=1073637 u=root n=ansible | to see the full traceback, use -vvv
2024-07-25 07:18:44,403 p=1073637 u=root n=ansible | the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 567, in run
    return context.CLIARGS['func']()
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 86, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 1201, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 1228, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3/dist-packages/ansible/galaxy/collection/__init__.py", line 513, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/usr/lib/python3/dist-packages/ansible/galaxy/collection/__init__.py", line 1327, in _resolve_depenency_map
    return collection_dep_resolver.resolve(
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 147, in _add_to_criteria
    matches = self._p.find_matches(
TypeError: CollectionDependencyProvider.find_matches() got an unexpected keyword argument 'identifier'

2024-07-25 07:26:50,555 p=1076976 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:26:50,556 p=1076976 u=core n=ansible | server3 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:26:50,854 p=1076976 u=core n=ansible | server1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 07:27:26,255 p=1076976 u=core n=ansible |  [ERROR]: User interrupted execution

2024-07-25 07:28:47,999 p=1077475 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 07:28:48,007 p=1077475 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 07:28:54,195 p=1077475 u=core n=ansible | ok: [server2]
2024-07-25 07:28:55,124 p=1077475 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:28:55,124 p=1077475 u=core n=ansible | ok: [server3]
2024-07-25 07:28:55,162 p=1077475 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 07:29:02,287 p=1077475 u=core n=ansible | fatal: [server3 -> server1(3.110.158.18)]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /home/core/Keys/KeyPair1_Mumbai.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/ubuntu/files/index.html ec2-user@3.6.41.146:/var/www/html/", "msg": "Warning: Identity file /home/core/Keys/KeyPair1_Mumbai.pem not accessible: No such file or directory.\nWarning: Permanently added '3.6.41.146' (ED25519) to the list of known hosts.\r\nec2-user@3.6.41.146: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]\n", "rc": 255}
2024-07-25 07:29:02,432 p=1077475 u=core n=ansible | fatal: [server2 -> server1(3.110.158.18)]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /home/core/Keys/KeyPair1_Mumbai.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/ubuntu/files/index.html ubuntu@65.0.107.56:/var/www/html/", "msg": "Warning: Identity file /home/core/Keys/KeyPair1_Mumbai.pem not accessible: No such file or directory.\nWarning: Permanently added '65.0.107.56' (ED25519) to the list of known hosts.\r\nubuntu@65.0.107.56: Permission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]\n", "rc": 255}
2024-07-25 07:29:02,434 p=1077475 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 07:29:02,435 p=1077475 u=core n=ansible | server2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:29:02,435 p=1077475 u=core n=ansible | server3                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:32:41,923 p=1078388 u=core n=ansible | PLAY [Install and configure Nginx for static website hosting] **************************************
2024-07-25 07:32:41,933 p=1078388 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 07:32:49,557 p=1078388 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:32:49,557 p=1078388 u=core n=ansible | ok: [server3]
2024-07-25 07:32:49,952 p=1078388 u=core n=ansible | ok: [server1]
2024-07-25 07:32:50,065 p=1078388 u=core n=ansible | ok: [server2]
2024-07-25 07:32:50,108 p=1078388 u=core n=ansible | TASK [Install Nginx] *******************************************************************************
2024-07-25 07:32:54,306 p=1078388 u=core n=ansible | [WARNING]: Updating cache and auto-installing missing dependency: python3-apt

2024-07-25 07:32:54,308 p=1078388 u=core n=ansible | fatal: [server3]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
2024-07-25 07:33:37,429 p=1078388 u=core n=ansible | changed: [server1]
2024-07-25 07:33:41,289 p=1078388 u=core n=ansible | changed: [server2]
2024-07-25 07:33:41,306 p=1078388 u=core n=ansible | TASK [Ensure Nginx is running] *********************************************************************
2024-07-25 07:33:45,889 p=1078388 u=core n=ansible | ok: [server1]
2024-07-25 07:33:48,345 p=1078388 u=core n=ansible | fatal: [server2]: FAILED! => {"changed": false, "msg": "Unable to start service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xeu nginx.service\" for details.\n"}
2024-07-25 07:33:48,378 p=1078388 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 07:33:48,378 p=1078388 u=core n=ansible | server1                    : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 07:33:48,378 p=1078388 u=core n=ansible | server2                    : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:33:48,379 p=1078388 u=core n=ansible | server3                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:36:31,030 p=1079331 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 07:36:31,038 p=1079331 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 07:36:38,412 p=1079331 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:36:38,413 p=1079331 u=core n=ansible | ok: [server3]
2024-07-25 07:36:38,971 p=1079331 u=core n=ansible | ok: [server2]
2024-07-25 07:36:39,006 p=1079331 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 07:36:39,068 p=1079331 u=core n=ansible | fatal: [server2 -> prod]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname prod: Name or service not known", "unreachable": true}
2024-07-25 07:36:39,085 p=1079331 u=core n=ansible | fatal: [server3 -> prod]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname prod: Name or service not known", "unreachable": true}
2024-07-25 07:36:39,087 p=1079331 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 07:36:39,087 p=1079331 u=core n=ansible | server2                    : ok=1    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 07:36:39,087 p=1079331 u=core n=ansible | server3                    : ok=1    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 07:38:46,642 p=1079840 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 07:38:46,650 p=1079840 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 07:38:54,075 p=1079840 u=core n=ansible | ok: [server2]
2024-07-25 07:38:54,237 p=1079840 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:38:54,238 p=1079840 u=core n=ansible | ok: [server3]
2024-07-25 07:38:54,275 p=1079840 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 07:39:01,526 p=1079840 u=core n=ansible | fatal: [server3 -> server1(3.110.158.18)]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /home/core/Keys/KeyPair1_Mumbai.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/ubuntu/files/index.html ec2-user@3.6.41.146:/var/www/html/", "msg": "Warning: Identity file /home/core/Keys/KeyPair1_Mumbai.pem not accessible: No such file or directory.\nWarning: Permanently added '3.6.41.146' (ED25519) to the list of known hosts.\r\nec2-user@3.6.41.146: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]\n", "rc": 255}
2024-07-25 07:39:01,654 p=1079840 u=core n=ansible | fatal: [server2 -> server1(3.110.158.18)]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /home/core/Keys/KeyPair1_Mumbai.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/ubuntu/files/index.html ubuntu@65.0.107.56:/var/www/html/", "msg": "Warning: Identity file /home/core/Keys/KeyPair1_Mumbai.pem not accessible: No such file or directory.\nWarning: Permanently added '65.0.107.56' (ED25519) to the list of known hosts.\r\nubuntu@65.0.107.56: Permission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]\n", "rc": 255}
2024-07-25 07:39:01,656 p=1079840 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 07:39:01,656 p=1079840 u=core n=ansible | server2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:39:01,656 p=1079840 u=core n=ansible | server3                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:43:17,245 p=1080892 u=core n=ansible | ERROR! conflicting action statements: synchronize, private_key

The error appears to be in '/home/core/Ansible/playbooks/copy.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Transfer file from ServerA to ServerB
      ^ here

2024-07-25 07:44:21,558 p=1081141 u=core n=ansible | ERROR! conflicting action statements: ansible.posix.synchronize, private_key

The error appears to be in '/home/core/Ansible/playbooks/copy.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Transfer file from ServerA to ServerB
      ^ here

2024-07-25 07:45:38,822 p=1081440 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 07:45:38,860 p=1081440 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 07:45:46,348 p=1081440 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 07:45:46,349 p=1081440 u=core n=ansible | ok: [server3]
2024-07-25 07:45:46,417 p=1081440 u=core n=ansible | ok: [server2]
2024-07-25 07:45:46,453 p=1081440 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 07:45:53,302 p=1081440 u=core n=ansible | fatal: [server2 -> server1(3.110.158.18)]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /home/core/Keys/KeyPair1_Mumbai.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/ubuntu/files/index.html ubuntu@65.0.107.56:/var/www/html/", "msg": "Warning: Identity file /home/core/Keys/KeyPair1_Mumbai.pem not accessible: No such file or directory.\nWarning: Permanently added '65.0.107.56' (ED25519) to the list of known hosts.\r\nubuntu@65.0.107.56: Permission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]\n", "rc": 255}
2024-07-25 07:45:53,309 p=1081440 u=core n=ansible | fatal: [server3 -> server1(3.110.158.18)]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /home/core/Keys/KeyPair1_Mumbai.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/ubuntu/files/index.html ec2-user@3.6.41.146:/var/www/html/", "msg": "Warning: Identity file /home/core/Keys/KeyPair1_Mumbai.pem not accessible: No such file or directory.\nWarning: Permanently added '3.6.41.146' (ED25519) to the list of known hosts.\r\nec2-user@3.6.41.146: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]\n", "rc": 255}
2024-07-25 07:45:53,311 p=1081440 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 07:45:53,311 p=1081440 u=core n=ansible | server2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 07:45:53,311 p=1081440 u=core n=ansible | server3                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 08:15:58,666 p=1088222 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 08:15:58,704 p=1088222 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 08:16:06,081 p=1088222 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 08:16:06,083 p=1088222 u=core n=ansible | ok: [server3]
2024-07-25 08:16:06,322 p=1088222 u=core n=ansible | ok: [server2]
2024-07-25 08:16:06,361 p=1088222 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 08:16:12,589 p=1088222 u=core n=ansible | changed: [server3 -> server1(3.110.158.18)]
2024-07-25 08:16:12,675 p=1088222 u=core n=ansible | changed: [server2 -> server1(3.110.158.18)]
2024-07-25 08:16:12,728 p=1088222 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 08:16:12,728 p=1088222 u=core n=ansible | server2                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 08:16:12,728 p=1088222 u=core n=ansible | server3                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 08:20:50,213 p=1089336 u=core n=ansible | PLAY [prod] ****************************************************************************************
2024-07-25 08:20:50,247 p=1089336 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 08:20:57,771 p=1089336 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 08:20:57,773 p=1089336 u=core n=ansible | ok: [server3]
2024-07-25 08:20:57,943 p=1089336 u=core n=ansible | ok: [server2]
2024-07-25 08:20:57,980 p=1089336 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 08:21:05,357 p=1089336 u=core n=ansible | ok: [server3 -> server1(3.110.158.18)]
2024-07-25 08:21:05,358 p=1089336 u=core n=ansible | ok: [server2 -> server1(3.110.158.18)]
2024-07-25 08:21:05,407 p=1089336 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 08:21:05,407 p=1089336 u=core n=ansible | server2                    : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 08:21:05,407 p=1089336 u=core n=ansible | server3                    : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 08:23:12,569 p=1089893 u=core n=ansible | PLAY [prod] ****************************************************************************************
2024-07-25 08:23:12,610 p=1089893 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 08:23:19,678 p=1089893 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 08:23:19,678 p=1089893 u=core n=ansible | ok: [server3]
2024-07-25 08:23:19,837 p=1089893 u=core n=ansible | ok: [server2]
2024-07-25 08:23:19,874 p=1089893 u=core n=ansible | TASK [Transfer file from ServerA to ServerB] *******************************************************
2024-07-25 08:23:27,334 p=1089893 u=core n=ansible | changed: [server2 -> server1(3.110.158.18)]
2024-07-25 08:23:27,442 p=1089893 u=core n=ansible | changed: [server3 -> server1(3.110.158.18)]
2024-07-25 08:23:27,497 p=1089893 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 08:23:27,497 p=1089893 u=core n=ansible | server2                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 08:23:27,497 p=1089893 u=core n=ansible | server3                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 09:08:04,889 p=1099959 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 09:08:04,890 p=1099959 u=core n=ansible | server3 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 09:08:05,113 p=1099959 u=core n=ansible | server2 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2024-07-25 10:08:46,280 p=1113594 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 10:08:46,294 p=1113594 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 10:08:53,855 p=1113594 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 10:08:53,856 p=1113594 u=core n=ansible | ok: [server3]
2024-07-25 10:08:53,899 p=1113594 u=core n=ansible | ok: [server2]
2024-07-25 10:08:53,932 p=1113594 u=core n=ansible | TASK [user-management : Create the user 'mohit'] ***************************************************
2024-07-25 10:08:57,952 p=1113594 u=core n=ansible | changed: [server2]
2024-07-25 10:08:58,064 p=1113594 u=core n=ansible | changed: [server3]
2024-07-25 10:08:58,076 p=1113594 u=core n=ansible | TASK [user-management : Add 'mohit' to the sudoers group] ******************************************
2024-07-25 10:09:01,686 p=1113594 u=core n=ansible | fatal: [server2]: FAILED! => {"changed": false, "msg": "Destination /etc/sudoers.d/mohit_nopasswd does not exist !", "rc": 257}
2024-07-25 10:09:01,752 p=1113594 u=core n=ansible | fatal: [server3]: FAILED! => {"changed": false, "msg": "Destination /etc/sudoers.d/mohit_nopasswd does not exist !", "rc": 257}
2024-07-25 10:09:01,755 p=1113594 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 10:09:01,756 p=1113594 u=core n=ansible | server2                    : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 10:09:01,756 p=1113594 u=core n=ansible | server3                    : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-07-25 10:18:06,171 p=1115736 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 10:18:06,182 p=1115736 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 10:18:14,125 p=1115736 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 10:18:14,125 p=1115736 u=core n=ansible | ok: [server3]
2024-07-25 10:18:14,142 p=1115736 u=core n=ansible | ok: [server2]
2024-07-25 10:18:14,175 p=1115736 u=core n=ansible | TASK [user-management : Create the user 'mohit'] ***************************************************
2024-07-25 10:18:18,271 p=1115736 u=core n=ansible | ok: [server2]
2024-07-25 10:18:18,437 p=1115736 u=core n=ansible | ok: [server3]
2024-07-25 10:18:18,453 p=1115736 u=core n=ansible | TASK [user-management : Add 'mohit' to the sudoers group] ******************************************
2024-07-25 10:18:22,420 p=1115736 u=core n=ansible | changed: [server2]
2024-07-25 10:18:22,796 p=1115736 u=core n=ansible | changed: [server3]
2024-07-25 10:18:22,811 p=1115736 u=core n=ansible | TASK [user-management : Add ssh key for user mohit] ************************************************
2024-07-25 10:18:27,015 p=1115736 u=core n=ansible | changed: [server2]
2024-07-25 10:18:27,080 p=1115736 u=core n=ansible | changed: [server3]
2024-07-25 10:18:27,165 p=1115736 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 10:18:27,165 p=1115736 u=core n=ansible | server2                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 10:18:27,165 p=1115736 u=core n=ansible | server3                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 11:20:17,373 p=1129576 u=core n=ansible | [DEPRECATION WARNING]: Specifying a list of dictionaries for vars is deprecated in favor of 
specifying a dictionary. This feature will be removed in version 2.18. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
2024-07-25 11:20:17,375 p=1129576 u=core n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in '/home/core/Ansible/playbooks/roles/user-management/tasks/main.yml': line 3, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  user:
    name: {{ user }}
           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2024-07-25 11:22:13,749 p=1130028 u=core n=ansible | [DEPRECATION WARNING]: Specifying a list of dictionaries for vars is deprecated in favor of 
specifying a dictionary. This feature will be removed in version 2.18. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
2024-07-25 11:22:13,804 p=1130028 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 11:22:13,814 p=1130028 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 11:22:21,441 p=1130028 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 11:22:21,442 p=1130028 u=core n=ansible | ok: [server3]
2024-07-25 11:22:21,809 p=1130028 u=core n=ansible | ok: [server2]
2024-07-25 11:22:21,844 p=1130028 u=core n=ansible | TASK [user-management : Create the user 'mohit'] ***************************************************
2024-07-25 11:22:25,773 p=1130028 u=core n=ansible | changed: [server2]
2024-07-25 11:22:26,142 p=1130028 u=core n=ansible | changed: [server3]
2024-07-25 11:22:26,159 p=1130028 u=core n=ansible | TASK [user-management : Add 'mohit' to the sudoers group] ******************************************
2024-07-25 11:22:29,769 p=1130028 u=core n=ansible | ok: [server2]
2024-07-25 11:22:29,907 p=1130028 u=core n=ansible | ok: [server3]
2024-07-25 11:22:29,919 p=1130028 u=core n=ansible | TASK [user-management : Add ssh key for user mohit] ************************************************
2024-07-25 11:22:33,540 p=1130028 u=core n=ansible | changed: [server2]
2024-07-25 11:22:33,743 p=1130028 u=core n=ansible | changed: [server3]
2024-07-25 11:22:33,801 p=1130028 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 11:22:33,801 p=1130028 u=core n=ansible | server2                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 11:22:33,801 p=1130028 u=core n=ansible | server3                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 11:44:32,100 p=1135002 u=core n=ansible | [DEPRECATION WARNING]: Specifying a list of dictionaries for vars is deprecated in favor of 
specifying a dictionary. This feature will be removed in version 2.18. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
2024-07-25 11:44:32,165 p=1135002 u=core n=ansible | PLAY [dev] *****************************************************************************************
2024-07-25 11:44:32,178 p=1135002 u=core n=ansible | TASK [Gathering Facts] *****************************************************************************
2024-07-25 11:44:39,610 p=1135002 u=core n=ansible | ok: [server2]
2024-07-25 11:44:39,616 p=1135002 u=core n=ansible | [WARNING]: Platform linux on host server3 is using the discovered Python interpreter at
/usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.

2024-07-25 11:44:39,617 p=1135002 u=core n=ansible | ok: [server3]
2024-07-25 11:44:39,656 p=1135002 u=core n=ansible | TASK [user-management : Create the user "sasuke"] **************************************************
2024-07-25 11:44:43,466 p=1135002 u=core n=ansible | changed: [server2]
2024-07-25 11:44:43,682 p=1135002 u=core n=ansible | changed: [server3]
2024-07-25 11:44:43,698 p=1135002 u=core n=ansible | TASK [user-management : Add "sasuke" to the sudoers group] *****************************************
2024-07-25 11:44:47,130 p=1135002 u=core n=ansible | changed: [server2]
2024-07-25 11:44:47,253 p=1135002 u=core n=ansible | changed: [server3]
2024-07-25 11:44:47,270 p=1135002 u=core n=ansible | TASK [user-management : Add ssh key for user "sasuke"] *********************************************
2024-07-25 11:44:51,055 p=1135002 u=core n=ansible | changed: [server2]
2024-07-25 11:44:51,144 p=1135002 u=core n=ansible | changed: [server3]
2024-07-25 11:44:51,212 p=1135002 u=core n=ansible | PLAY RECAP *****************************************************************************************
2024-07-25 11:44:51,214 p=1135002 u=core n=ansible | server2                    : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-07-25 11:44:51,214 p=1135002 u=core n=ansible | server3                    : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
